### PR TITLE
Adding Poster.html

### PR DESCRIPTION
**Pull request by jamil2388**
I worked on below additions to the existing pages :

- Added lab/poster.html
- Kept basic header, footer and "Recent News" panel constant
- Inserted relevant clickable images of the posters as tiles
- The images create hover effect upon mouse movement
- Added relevant description about the venues (if applicable)
- Replicated redirect buttons and their functionalities from the publication page
- Added "poster" tab in all other existing pages for quick navigation
- Gave relevant information and redirection links based on available info. The link buttons like doi, git might need updating the attached links

### CODE REVIEW

**Comment by hosseinfani** [comment]
@jamil2388 thank you very much. Just few more revisions please:
- make the "poster" button link to the pdf of the poster (currently it's link to image)
- rename the "pdf" button to "paper", if there is a paper associated with the poster. If not, don't put that button
- compress the image files of the poster to 30-50Kb so the page loads faster
- more the ./res/posters/img folder to ./lab/img/poster

**Comment by jamil2388** [comment]
@hosseinfani,
Right now I have the buttons poster, pdf, doi and git under each poster thumbnail. Most of the posters dont have a doi involved, so I have them pointed to blank. 
- Do I still keep the doi's?
- Do I redirect the user to poster image or pdf when the main thumbnail is clicked?

Thanks!

**Comment by jamil2388** [comment]
Hi @hosseinfani ,

- Most of the poster presentations didnt have any papers associated to them, but some of them have a publication now, do I need to include that publication there? Or ignore?
- Do I need to keep the doi button? Most of them doesnt have any paper associated as of now

**Comment by hosseinfani** [comment]
Hi @jamil2388 
put the html tags, but comment them out. So, in the surface, there will be no button if there is no link to an actual paper or doi. thank you.

**Pull request merged**
